### ISSUE TITLE
Consider moving this project to the official Aleut org.?

### ISSUE THREAD

**Issue by kmelve** [TiuSh/meteor-aleutcss#1]
Hi @TiuSh!

We love that you made this package for react and meteor! Would you consider maintaining this project over at https://github.com/aleutcss? 

Give me a shout and I'll invite you as a member of the organization and you can move your project  there.

**Comment by TiuSh** [comment]
Surely @kmelve !

**Comment by robinsandborg** [comment]
Hey @TiuSh, I’ve added you to our organization now.

**Comment by TiuSh** [comment]
Hi @robinsandborg,

Thank you for adding me, I'm updating the README and duplicating the repo on your organization. By the way the repo is also linked to a meteor package repo : https://atmospherejs.com/tiush/aleutcss
I think you should create a Meteor Developer Account for aleut.css, publish a new package (https://atmospherejs.com/i/publishing), and then I will remove mine. If you need any help on this, please tell me.
